In [1]:
import pandas as pd

In [2]:
income_table = pd.read_csv('productDownload_2022-01-24T145502/State_by_State_Income_Info.csv')

In [3]:
# create function to delete columns based on name
def deleteColumnNames(table, str):
    index = []
    for name in table.columns:
        if str in name:
            index.append(name)
    table = table.drop(columns = index, axis = 0)
    return table;

In [4]:
income_table.head()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [5]:
# remove id column
income_table = deleteColumnNames(income_table, 'id')
income_table.head()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [6]:
# cleaning cleaning strings to have a space instead of !!
rowOne =income_table.loc[0]
titleArray = []
for title in rowOne:
    title = title.replace('!!', ' ')
    titleArray.append(title)
income_table.loc[0] = titleArray

In [7]:
income_table.columns = income_table.loc[0]

,id,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000","Margin of Error Households Total Less than $10,000","Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $14,999","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $24,999",...,Estimate Nonfamily households Median income (dollars),Margin of Error Nonfamily households Median income (dollars),Estimate Nonfamily households Mean income (dollars),Margin of Error Nonfamily households Mean income (dollars),Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
0,id,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000",Margin of Error Households Total Less than $10...,"Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $1...","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $2...",...,Estimate Nonfamily households Median income (d...,Margin of Error Nonfamily households Median in...,Estimate Nonfamily households Mean income (dol...,Margin of Error Nonfamily households Mean inco...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [8]:
income_table = income_table.drop(labels=0, axis=0)

In [9]:
for name in income_table.columns:
    print(name)

id
Geographic Area Name
Estimate Households Total
Margin of Error Households Total
Estimate Households Total Less than $10,000
Margin of Error Households Total Less than $10,000
Estimate Households Total $10,000 to $14,999
Margin of Error Households Total $10,000 to $14,999
Estimate Households Total $15,000 to $24,999
Margin of Error Households Total $15,000 to $24,999
Estimate Households Total $25,000 to $34,999
Margin of Error Households Total $25,000 to $34,999
Estimate Households Total $35,000 to $49,999
Margin of Error Households Total $35,000 to $49,999
Estimate Households Total $50,000 to $74,999
Margin of Error Households Total $50,000 to $74,999
Estimate Households Total $75,000 to $99,999
Margin of Error Households Total $75,000 to $99,999
Estimate Households Total $100,000 to $149,999
Margin of Error Households Total $100,000 to $149,999
Estimate Households Total $150,000 to $199,999
Margin of Error Households Total $150,000 to $199,999
Estimate Households Total $200,000 or more
Margin of Error Households Total $200,000 or more
Estimate Households Median income (dollars)
Margin of Error Households Median income (dollars)
Estimate Households Mean income (dollars)
Margin of Error Households Mean income (dollars)
Estimate Households PERCENT ALLOCATED Household income in the past 12 months
Margin of Error Households PERCENT ALLOCATED Household income in the past 12 months
Estimate Households PERCENT ALLOCATED Family income in the past 12 months
Margin of Error Households PERCENT ALLOCATED Family income in the past 12 months
Estimate Households PERCENT ALLOCATED Nonfamily income in the past 12 months
Margin of Error Households PERCENT ALLOCATED Nonfamily income in the past 12 months
Estimate Families Total
Margin of Error Families Total
Estimate Families Total Less than $10,000
Margin of Error Families Total Less than $10,000
Estimate Families Total $10,000 to $14,999
Margin of Error Families Total $10,000 to $14,999
Estimate Families Total $15,000 to $24,999
Margin of Error Families Total $15,000 to $24,999
Estimate Families Total $25,000 to $34,999
Margin of Error Families Total $25,000 to $34,999
Estimate Families Total $35,000 to $49,999
Margin of Error Families Total $35,000 to $49,999
Estimate Families Total $50,000 to $74,999
Margin of Error Families Total $50,000 to $74,999
Estimate Families Total $75,000 to $99,999
Margin of Error Families Total $75,000 to $99,999
Estimate Families Total $100,000 to $149,999
Margin of Error Families Total $100,000 to $149,999
Estimate Families Total $150,000 to $199,999
Margin of Error Families Total $150,000 to $199,999
Estimate Families Total $200,000 or more
Margin of Error Families Total $200,000 or more
Estimate Families Median income (dollars)
Margin of Error Families Median income (dollars)
Estimate Families Mean income (dollars)
Margin of Error Families Mean income (dollars)
Estimate Families PERCENT ALLOCATED Household income in the past 12 months
Margin of Error Families PERCENT ALLOCATED Household income in the past 12 months
Estimate Families PERCENT ALLOCATED Family income in the past 12 months
Margin of Error Families PERCENT ALLOCATED Family income in the past 12 months
Estimate Families PERCENT ALLOCATED Nonfamily income in the past 12 months
Margin of Error Families PERCENT ALLOCATED Nonfamily income in the past 12 months
Estimate Married-couple families Total
Margin of Error Married-couple families Total
Estimate Married-couple families Total Less than $10,000
Margin of Error Married-couple families Total Less than $10,000
Estimate Married-couple families Total $10,000 to $14,999
Margin of Error Married-couple families Total $10,000 to $14,999
Estimate Married-couple families Total $15,000 to $24,999
Margin of Error Married-couple families Total $15,000 to $24,999
Estimate Married-couple families Total $25,000 to $34,999
Margin of Error Married-couple families Total $25,000 to $34,999
Estimate Married-couple families Total $35,000 to $49,999
Margin of Error Married-couple families Total $35,000 to $49,999
Estimate Married-couple families Total $50,000 to $74,999
Margin of Error Married-couple families Total $50,000 to $74,999
Estimate Married-couple families Total $75,000 to $99,999
Margin of Error Married-couple families Total $75,000 to $99,999
Estimate Married-couple families Total $100,000 to $149,999
Margin of Error Married-couple families Total $100,000 to $149,999
Estimate Married-couple families Total $150,000 to $199,999
Margin of Error Married-couple families Total $150,000 to $199,999
Estimate Married-couple families Total $200,000 or more
Margin of Error Married-couple families Total $200,000 or more
Estimate Married-couple families Median income (dollars)
Margin of Error Married-couple families Median income (dollars)
Estimate Married-couple families Mean income (dollars)
Margin of Error Married-couple families Mean income (dollars)
Estimate Married-couple families PERCENT ALLOCATED Household income in the past 12 months
Margin of Error Married-couple families PERCENT ALLOCATED Household income in the past 12 months
Estimate Married-couple families PERCENT ALLOCATED Family income in the past 12 months
Margin of Error Married-couple families PERCENT ALLOCATED Family income in the past 12 months
Estimate Married-couple families PERCENT ALLOCATED Nonfamily income in the past 12 months
Margin of Error Married-couple families PERCENT ALLOCATED Nonfamily income in the past 12 months
Estimate Nonfamily households Total
Margin of Error Nonfamily households Total
Estimate Nonfamily households Total Less than $10,000
Margin of Error Nonfamily households Total Less than $10,000
Estimate Nonfamily households Total $10,000 to $14,999
Margin of Error Nonfamily households Total $10,000 to $14,999
Estimate Nonfamily households Total $15,000 to $24,999
Margin of Error Nonfamily households Total $15,000 to $24,999
Estimate Nonfamily households Total $25,000 to $34,999
Margin of Error Nonfamily households Total $25,000 to $34,999
Estimate Nonfamily households Total $35,000 to $49,999
Margin of Error Nonfamily households Total $35,000 to $49,999
Estimate Nonfamily households Total $50,000 to $74,999
Margin of Error Nonfamily households Total $50,000 to $74,999
Estimate Nonfamily households Total $75,000 to $99,999
Margin of Error Nonfamily households Total $75,000 to $99,999
Estimate Nonfamily households Total $100,000 to $149,999
Margin of Error Nonfamily households Total $100,000 to $149,999
Estimate Nonfamily households Total $150,000 to $199,999
Margin of Error Nonfamily households Total $150,000 to $199,999
Estimate Nonfamily households Total $200,000 or more
Margin of Error Nonfamily households Total $200,000 or more
Estimate Nonfamily households Median income (dollars)
Margin of Error Nonfamily households Median income (dollars)
Estimate Nonfamily households Mean income (dollars)
Margin of Error Nonfamily households Mean income (dollars)
Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months
Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months
Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months
Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months
Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months

In [10]:
deleteColumnNames(income_table, 'id')

,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000","Margin of Error Households Total Less than $10,000","Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $14,999","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $24,999","Estimate Households Total $25,000 to $34,999",...,Estimate Nonfamily households Median income (dollars),Margin of Error Nonfamily households Median income (dollars),Estimate Nonfamily households Mean income (dollars),Margin of Error Nonfamily households Mean income (dollars),Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
1,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,10.3,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,6.9,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,8.6,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,11.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)
5,California,13157873,23844,4.6,0.1,3.7,0.1,6.6,0.1,6.8,...,51676,389,78815,718,(X),(X),(X),(X),32.9,(X)
6,Colorado,2235103,10026,4.6,0.3,2.9,0.2,6.2,0.3,6.7,...,50092,1094,67652,1593,(X),(X),(X),(X),33.5,(X)
7,Connecticut,1377166,6712,5.3,0.3,3.6,0.3,7.2,0.4,6.8,...,45001,1453,64185,2107,(X),(X),(X),(X),33.5,(X)
8,Delaware,376239,3536,5.4,0.7,3.6,0.5,7.1,0.8,7.2,...,44071,2049,58190,2619,(X),(X),(X),(X),41.5,(X)
9,District of Columbia,291570,3959,8.0,0.9,3.3,0.7,4.9,0.8,4.6,...,76529,2303,101740,3753,(X),(X),(X),(X),26.1,(X)
10,Florida,7905832,23042,6.0,0.2,4.0,0.1,9.0,0.2,9.6,...,37292,388,54820,762,(X),(X),(X),(X),35.1,(X)
11,Georgia,3852714,14425,6.2,0.2,4.3,0.2,8.8,0.3,8.9,...,37881,841,53872,1103,(X),(X),(X),(X),33.1,(X)
12,Hawaii,465299,5012,5.0,0.5,2.6,0.4,5.9,0.7,6.4,...,51343,2150,70211,3294,(X),(X),(X),(X),35.0,(X)
13,Idaho,655859,5316,4.2,0.5,3.7,0.4,9.1,0.6,9.6,...,35157,1498,47069,1853,(X),(X),(X),(X),28.7,(X)
14,Illinois,4866006,12627,5.9,0.2,3.7,0.2,8.0,0.2,8.0,...,40860,436,58746,999,(X),(X),(X),(X),32.2,(X)
15,Indiana,2597765,12716,5.9,0.3,4.0,0.2,9.4,0.3,9.8,...,33994,795,46287,876,(X),(X),(X),(X),32.3,(X)
16,Iowa,1287221,6606,5.1,0.3,4.1,0.3,8.4,0.4,9.1,...,36559,757,48007,1106,(X),(X),(X),(X),31.9,(X)
17,Kansas,1138329,6595,5.1,0.4,4.3,0.3,8.3,0.4,8.9,...,36347,714,48152,1442,(X),(X),(X),(X),30.8,(X)
18,Kentucky,1748732,8789,7.9,0.4,5.5,0.3,10.8,0.4,10.0,...,30384,772,44650,1273,(X),(X),(X),(X),31.6,(X)
19,Louisiana,1741076,11011,10.1,0.4,5.7,0.3,11.3,0.5,9.9,...,28907,1010,45018,1710,(X),(X),(X),(X),38.5,(X)
20,Maine,573618,4999,5.1,0.5,4.7,0.5,9.5,0.5,9.7,...,35624,1461,49232,1473,(X),(X),(X),(X),29.3,(X)
21,Maryland,2226767,9709,4.8,0.3,2.6,0.2,5.6,0.3,6.3,...,51990,744,68930,1477,(X),(X),(X),(X),30.0,(X)
22,Massachusetts,2650680,9065,5.1,0.3,3.9,0.2,6.5,0.2,6.1,...,50338,967,72501,1706,(X),(X),(X),(X),35.1,(X)
23,Michigan,3969880,12901,6.2,0.2,4.1,0.2,9.0,0.3,9.7,...,35755,457,49460,860,(X),(X),(X),(X),32.6,(X)
24,Minnesota,2222568,7740,4.1,0.2,3.4,0.2,6.5,0.3,7.2,...,44136,810,58072,1082,(X),(X),(X),(X),28.9,(X)
25,Mississippi,1100229,9887,9.3,0.5,6.6,0.5,12.5,0.6,11.2,...,25562,730,39081,2156,(X),(X),(X),(X),35.1,(X)
26,Missouri,2458337,10406,6.3,0.3,4.5,0.2,9.7,0.3,9.5,...,33821,843,47145,1047,(X),(X),(X),(X),29.9,(X)
27,Montana,437651,4637,5.4,0.5,4.9,0.5,10.1,0.6,9.1,...,34919,1469,48017,2222,(X),(X),(X),(X),31.8,(X)
28,Nebraska,771444,4475,4.8,0.4,3.9,0.3,8.0,0.5,8.7,...,37791,1205,50009,1405,(X),(X),(X),(X),33.8,(X)
29,Nevada,1143557,8281,6.0,0.4,3.9,0.3,7.9,0.5,8.1,...,41065,862,57718,1912,(X),(X),(X),(X),34.5,(X)
30,New Hampshire,541396,5389,3.9,0.5,3.1,0.5,6.5,0.6,6.8,...,45803,2182,59717,2399,(X),(X),(X),(X),29.0,(X)
31,New Jersey,3286264,9466,4.7,0.2,2.9,0.2,6.2,0.2,6.4,...,49643,1186,69872,1408,(X),(X),(X),(X),33.5,(X)
32,New Mexico,793420,7074,8.3,0.6,5.4,0.4,11.4,0.7,10.3,...,32958,1893,49307,1874,(X),(X),(X),(X),29.8,(X)
33,New York,7446812,13820,6.7,0.1,4.4,0.1,7.7,0.2,7.2,...,44681,758,70514,1239,(X),(X),(X),(X),36.7,(X)
34,North Carolina,4046348,15467,6.2,0.2,4.6,0.2,9.6,0.3,9.7,...,34864,660,48461,791,(X),(X),(X),(X),32.5,(X)
35,North Dakota,323519,3879,5.4,0.6,4.5,0.6,7.8,0.8,8.9,...,38698,2584,51859,2749,(X),(X),(X),(X),33.3,(X)
36,Ohio,4730340,12955,6.3,0.2,4.3,0.2,9.5,0.2,9.7,...,35147,474,48381,725,(X),(X),(X),(X),30.0,(X)
37,Oklahoma,1495151,7032,6.9,0.3,4.8,0.2,10.1,0.3,10.1,...,32185,688,46171,1329,(X),(X),(X),(X),34.6,(X)
38,Oregon,1649352,8550,5.4,0.3,3.7,0.2,7.5,0.3,8.3,...,41733,840,57967,1397,(X),(X),(X),(X),29.4,(X)
39,Pennsylvania,5119249,11502,6.0,0.2,4.1,0.2,8.6,0.2,8.8,...,36748,424,53173,835,(X),(X),(X),(X),33.5,(X)
40,Rhode Island,407174,4739,5.6,0.7,4.5,0.6,7.7,0.8,7.7,...,40254,2280,54554,1852,(X),(X),(X),(X),36.4,(X)
41,South Carolina,1975915,11292,7.2,0.4,4.3,0.3,9.6,0.4,9.5,...,33610,1005,48320,1515,(X),(X),(X),(X),37.4,(X)
42,South Dakota,353799,3905,4.7,0.5,4.3,0.5,9.1,0.7,9.8,...,35697,1411,47350,2164,(X),(X),(X),(X),29.4,(X)
43,Tennessee,2654737,12964,6.2,0.2,5.0,0.3,9.7,0.3,10.0,...,33992,893,47167,1126,(X),(X),(X),(X),32.4,(X)
44,Texas,9985126,25440,5.9,0.2,3.7,0.1,8.5,0.2,8.5,...,40389,380,55749,622,(X),(X),(X),(X),30.2,(X)
45,Utah,1023855,5773,3.6,0.3,2.8,0.3,6.0,0.4,7.1,...,42659,1802,58132,2409,(X),(X),(X),(X),31.2,(X)
46,Vermont,262767,3459,5.2,0.8,4.4,0.7,7.8,0.8,9.2,...,38034,1984,50348,2094,(X),(X),(X),(X),29.7,(X)
47,Virginia,3191847,12998,4.8,0.2,3.2,0.2,7.0,0.3,7.2,...,46570,802,66117,1272,(X),(X),(X),(X),31.3,(X)
48,Washington,2932477,11062,4.4,0.2,3.0,0.2,6.5,0.3,6.6,...,50045,955,69816,1159,(X),(X),(X),(X),27.3,(X)
49,West Virginia,728175,7273,8.5,0.6,5.9,0.5,11.4,0.6,10.8,...,26752,860,40541,1769,(X),(X),(X),(X),32.0,(X)
50,Wisconsin,2386623,7340,4.4,0.2,4.0,0.2,8.4,0.3,8.7,...,38937,808,50592,822,(X),(X),(X),(X),30.4,(X)
51,Wyoming,233128,3322,5.0,0.8,4.1,0.8,8.2,0.9,8.6,...,37299,4175,51642,3561,(X),(X),(X),(X),31.9,(X)
52,Puerto Rico,1170982,9101,26.8,0.7,11.8,0.3,18.6,0.6,12.5,...,12051,384,20281,610,(X),(X),(X),(X),27.9,(X)

In [11]:
noMarginofError = income_table.drop(columns=index, axis=0)
noMarginofError = noMarginofError.drop(columns = 'id', axis = 0)

NameError: name 'index' is not defined

In [ ]:
noMarginofError.head()