In [1]:
import pandas as pd

In [2]:
income_table = pd.read_csv('productDownload_2022-01-24T145502/State_by_State_Income_Info.csv')

In [3]:
income_table.head(10)

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)
5,0400000US06,California,13157873,23844,4.6,0.1,3.7,0.1,6.6,0.1,...,51676,389,78815,718,(X),(X),(X),(X),32.9,(X)
6,0400000US08,Colorado,2235103,10026,4.6,0.3,2.9,0.2,6.2,0.3,...,50092,1094,67652,1593,(X),(X),(X),(X),33.5,(X)
7,0400000US09,Connecticut,1377166,6712,5.3,0.3,3.6,0.3,7.2,0.4,...,45001,1453,64185,2107,(X),(X),(X),(X),33.5,(X)
8,0400000US10,Delaware,376239,3536,5.4,0.7,3.6,0.5,7.1,0.8,...,44071,2049,58190,2619,(X),(X),(X),(X),41.5,(X)
9,0400000US11,District of Columbia,291570,3959,8.0,0.9,3.3,0.7,4.9,0.8,...,76529,2303,101740,3753,(X),(X),(X),(X),26.1,(X)

In [4]:
rowOne =income_table.loc[0]
titleArray = []
for title in rowOne:
    title = title.replace('!!', ' ')
    titleArray.append(title)
income_table.loc[0] = titleArray
income_table.head()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000",Margin of Error Households Total Less than $10...,"Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $1...","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $2...",...,Estimate Nonfamily households Median income (d...,Margin of Error Nonfamily households Median in...,Estimate Nonfamily households Mean income (dol...,Margin of Error Nonfamily households Mean inco...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [5]:
income_table.columns = income_table.loc[0]
income_table.head()

,id,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000","Margin of Error Households Total Less than $10,000","Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $14,999","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $24,999",...,Estimate Nonfamily households Median income (dollars),Margin of Error Nonfamily households Median income (dollars),Estimate Nonfamily households Mean income (dollars),Margin of Error Nonfamily households Mean income (dollars),Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
0,id,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000",Margin of Error Households Total Less than $10...,"Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $1...","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $2...",...,Estimate Nonfamily households Median income (d...,Margin of Error Nonfamily households Median in...,Estimate Nonfamily households Mean income (dol...,Margin of Error Nonfamily households Mean inco...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [7]:
income_table = income_table.drop(labels=0, axis=0)

In [9]:
income_table.dtypes

0
id                                                                                               object
Geographic Area Name                                                                             object
Estimate Households Total                                                                        object
Margin of Error Households Total                                                                 object
Estimate Households Total Less than $10,000                                                      object
                                                                                                  ...
Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months    object
Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months              object
Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months       object
Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months           object
Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months    object
Length: 130, dtype: object