In [1]:
import pandas as pd

In [2]:
income_table = pd.read_csv('productDownload_2022-01-24T145502/State_by_State_Income_Info.csv')

In [3]:
# create function to delete columns based on name
def deleteColumnNames(table, str):
    index = []
    for name in table.columns:
        if str in name:
            index.append(name)
    table = table.drop(columns = index, axis = 0)
    return table;

In [4]:
income_table.head()

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...
1,0400000US01,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,0400000US02,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,0400000US04,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,0400000US05,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [5]:
# remove id column
income_table = deleteColumnNames(income_table, 'GEO_ID')

income_table.head()

,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,S1901_C01_005E,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...","Estimate!!Households!!Total!!$25,000 to $34,999",...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...
1,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,10.3,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,6.9,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,8.6,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,11.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [6]:
# replace !! with a space in the column names
rowOne =income_table.loc[0]
titleArray = []
for title in rowOne:
    title = title.replace('!!', ' ')
    titleArray.append(title)
income_table.loc[0] = titleArray
income_table.head()

,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,S1901_C01_005E,...,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M
0,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000",Margin of Error Households Total Less than $10...,"Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $1...","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $2...","Estimate Households Total $25,000 to $34,999",...,Estimate Nonfamily households Median income (d...,Margin of Error Nonfamily households Median in...,Estimate Nonfamily households Mean income (dol...,Margin of Error Nonfamily households Mean inco...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...,Estimate Nonfamily households PERCENT ALLOCATE...,Margin of Error Nonfamily households PERCENT A...
1,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,10.3,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,6.9,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,8.6,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,11.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)

In [7]:
# replace column names with first row names
income_table.columns = income_table.loc[0]

In [9]:
# drop duplicate column names
income_table = income_table.drop(labels=0, axis=0)

In [10]:
income_table.head()

,Geographic Area Name,Estimate Households Total,Margin of Error Households Total,"Estimate Households Total Less than $10,000","Margin of Error Households Total Less than $10,000","Estimate Households Total $10,000 to $14,999","Margin of Error Households Total $10,000 to $14,999","Estimate Households Total $15,000 to $24,999","Margin of Error Households Total $15,000 to $24,999","Estimate Households Total $25,000 to $34,999",...,Estimate Nonfamily households Median income (dollars),Margin of Error Nonfamily households Median income (dollars),Estimate Nonfamily households Mean income (dollars),Margin of Error Nonfamily households Mean income (dollars),Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months,Margin of Error Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
1,Alabama,1897576,10370,8.1,0.3,5.5,0.3,10.9,0.4,10.3,...,29458,1226,42510,1268,(X),(X),(X),(X),35.6,(X)
2,Alaska,252199,3658,4.1,0.6,3.2,0.5,6.6,0.8,6.9,...,47508,2524,61602,3112,(X),(X),(X),(X),29.3,(X)
3,Arizona,2670441,12014,5.9,0.3,3.5,0.2,8.2,0.3,8.6,...,40198,617,55773,1079,(X),(X),(X),(X),32.0,(X)
4,Arkansas,1163647,8530,7.1,0.4,6.0,0.4,12.1,0.5,11.5,...,27607,862,40235,1392,(X),(X),(X),(X),36.1,(X)
5,California,13157873,23844,4.6,0.1,3.7,0.1,6.6,0.1,6.8,...,51676,389,78815,718,(X),(X),(X),(X),32.9,(X)

In [13]:
# delete margin of error columns
noMarginofError = deleteColumnNames(income_table, 'Margin of Error')
noMarginofError.head()

,Geographic Area Name,Estimate Households Total,"Estimate Households Total Less than $10,000","Estimate Households Total $10,000 to $14,999","Estimate Households Total $15,000 to $24,999","Estimate Households Total $25,000 to $34,999","Estimate Households Total $35,000 to $49,999","Estimate Households Total $50,000 to $74,999","Estimate Households Total $75,000 to $99,999","Estimate Households Total $100,000 to $149,999",...,"Estimate Nonfamily households Total $50,000 to $74,999","Estimate Nonfamily households Total $75,000 to $99,999","Estimate Nonfamily households Total $100,000 to $149,999","Estimate Nonfamily households Total $150,000 to $199,999","Estimate Nonfamily households Total $200,000 or more",Estimate Nonfamily households Median income (dollars),Estimate Nonfamily households Mean income (dollars),Estimate Nonfamily households PERCENT ALLOCATED Household income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Family income in the past 12 months,Estimate Nonfamily households PERCENT ALLOCATED Nonfamily income in the past 12 months
1,Alabama,1897576,8.1,5.5,10.9,10.3,13.4,17.8,11.2,13.4,...,14.6,5.6,5.5,1.4,1.1,29458,42510,(X),(X),35.6
2,Alaska,252199,4.1,3.2,6.6,6.9,10.7,18.1,13.4,18.2,...,18.5,12.6,10.8,2.6,3.0,47508,61602,(X),(X),29.3
3,Arizona,2670441,5.9,3.5,8.2,8.6,13.7,18.8,13.3,15.3,...,17.6,8.8,8.3,2.5,2.7,40198,55773,(X),(X),32.0
4,Arkansas,1163647,7.1,6.0,12.1,11.5,14.1,18.3,11.5,11.6,...,12.9,5.8,3.8,0.9,1.2,27607,40235,(X),(X),36.1
5,California,13157873,4.6,3.7,6.6,6.8,9.9,15.3,12.5,17.4,...,15.8,10.8,12.6,5.4,7.1,51676,78815,(X),(X),32.9